"""Create 'users' and 'items' table

Revision ID: 0f68be9f7068
Revises: 
Create Date: 2019-06-23 00:46:41.934487

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '0f68be9f7068'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    users = op.create_table('users',
                            sa.Column('id', sa.Integer(), nullable=False),
                            sa.Column('email', sa.String(), nullable=True),
                            sa.Column('hashed_password', sa.String(), nullable=True),
                            sa.Column('is_active', sa.Boolean(), nullable=True),
                            sa.PrimaryKeyConstraint('id')
                            )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    items = op.create_table('items',
                            sa.Column('id', sa.Integer(), nullable=False),
                            sa.Column('title', sa.String(), nullable=True),
                            sa.Column('description', sa.String(), nullable=True),
                            sa.Column('owner_id', sa.Integer(), nullable=True),
                            sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
                            sa.PrimaryKeyConstraint('id')
                            )
    op.create_index(op.f('ix_items_description'), 'items', ['description'], unique=False)
    op.create_index(op.f('ix_items_id'), 'items', ['id'], unique=False)
    op.create_index(op.f('ix_items_title'), 'items', ['title'], unique=False)

    # Bulk insert
    op.bulk_insert(users, [
        {
            'email': 'jude@terang.asia',
            'hashed_password': 'abc123'
        },
        {
            'email': 'aishaha@terang.asia',
            'hashed_password': 'abc123'
        },
        {
            'email': 'minmax@terang.asia',
            'hashed_password': 'abc123'
        },
        {
            'email': 'zaharin@terang.asia',
            'hashed_password': 'abc123'
        },

    ])

    op.bulk_insert(items, [
        {
            'title': 'DVD',
            'description': 'Into The Woods',
            'owner_id': '1'
        },
        {
            'title': 'DVD',
            'description': 'Die Hard 2',
            'owner_id': '1'
        },
        {
            'title': 'DVD',
            'description': 'Aladdin',
            'owner_id': '2'
        },
        {
            'title': 'DVD',
            'description': 'Pokemon',
            'owner_id': '2'
        },
        {
            'title': 'DVD',
            'description': 'Space Odyssey',
            'owner_id': '3'
        },
        {
            'title': 'DVD',
            'description': 'Inception',
            'owner_id': '3'
        },
        {
            'title': 'DVD',
            'description': 'Rocket Man',
            'owner_id': '4'
        },
    ])


# ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_items_title'), table_name='items')
    op.drop_index(op.f('ix_items_id'), table_name='items')
    op.drop_index(op.f('ix_items_description'), table_name='items')
    op.drop_table('items')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
# ### end Alembic commands ###
